name: Build Docker Image (Release)

on:
  push:
    tags:
      - "v*"

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build Docker Image
        uses: docker/build-push-action@v1
        with:
          push: false
          repository: recognizer-intermediate-artifacts
          tags: latest

      - name: Get Tag Version
        id: get_version
        run: |
          echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
          
      - uses: shrink/actions-docker-extract@v1
        id: extract
        with:
          image: recognizer-intermediate-artifacts:latest
          path: /build/recognizer/build/dist/.
      
      # zip files under /build/recognizer/build/dist/ to /build/recognizer/build/dist/${VERSION}.zip
      - name: Zip Files
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -j -r ${GITHUB_WORKSPACE}/${VERSION}.zip /build/recognizer/build/dist/

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            ${GITHUB_WORKSPACE}/${VERSION}.zip

      # - name: Upload Dist
      #   uses: actions/upload-artifact@v2
      #   with:
      #     path: ${{ steps.extract.outputs.destination }}
      #     name: penguin-recognizer-wasm
